 <div class="col-md-12 end-box ">
		<span style="margin-right:20px;">
		
	   <?php echo '<a href="'.MYSHOPTWO.'/terms-and-conditions.php">Ts & Cs</a> | <a href="'.MYSHOPTWO.'/how-it-works.php">How it works</a> | <a href="'.MYSHOPTWO.'/making-money-on-myshoptwo.php">How to earn</a>';?></span>  <?php echo '<a href="'.MYSHOPTWO.'">CLASSIFIED ADS</a>';?> <span style="margin-left:20px;">To advertise:  <?php echo AD_CONTACT_NUMBER; ?> </span>
     <br>&copy;
		<?php
		$copyyear = 2019;
		$curyear = date('Y');
		echo $copyyear. (($copyyear != $curyear)? '-' . $curyear : '');
		?> All Rights Reserved. |&nbsp;  Made by <a href="#" rel="nofollow" target="_blank">Classified Ads</a>
	</div>
    <!-- /.col -->
    <!--Footer end -->
   
	<script src="assets/js/jquery-1.10.2.js"></script>
	 <!--Core JavaScript file  -->
   
    <!--bootstrap JavaScript file  -->
    <script src="assets/js/bootstrap.js"></script>
	<!--slot game -->
	<script src="assets/ItemSlider/js/jquery.easing.1.3.js" type="text/javascript" charset="utf-8"></script>
    <script src="assets/ItemSlider/js/jquery.jSlots.min.js" type="text/javascript" charset="utf-8"></script>
	<!--Slider JavaScript file  -->
    <script src="assets/ItemSlider/js/modernizr.custom.63321.js"></script>
    <script src="assets/ItemSlider/js/jquery.catslider.js"></script>
    <script>
        $(function () {

            $('#mi-slider').catslider();

        });
	</script>
	<script type="text/javascript">
	$(document).ready(function(){$('#getrecordsabia').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "abia.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsadamawa').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "adamawa.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsakwaibom').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "akwaibom.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsanambra').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "anambra.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbauchi').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "bauchi.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbayelsa').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "bayelsa.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbenue').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "benue.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsborno').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "borno.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordscrossriver').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "crossriver.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsdelta').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "delta.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsebonyi').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ebonyi.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsedo').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "edo.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsekiti').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ekiti.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsenugu').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "enugu.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsgombe').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "gombe.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsimo').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "imo.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsjigawa').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "jigawa.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordskaduna').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kaduna.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordskano').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kano.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordskatsina').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "katsina.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordskebbi').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kebbi.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordskogi').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kogi.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordskwara').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kwara.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordslagos').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "lagos.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsnasarawa').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "nasarawa.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsniger').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "niger.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsogun').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ogun.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsondo').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ondo.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsosun').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "osun.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsoyo').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "oyo.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})	
	$(document).ready(function(){$('#getrecordsplateau').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "plateau.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsrivers').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "rivers.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordssokoto').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "sokoto.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordstaraba').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "taraba.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsyobe').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "yobe.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordszamfara').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "zamfara.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	$(document).ready(function(){$('#getrecordsfct').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "fct.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_post').html(text);}});});})
	</script>
	
	<script type="text/javascript">
	$(document).ready(function(){$('#getrecordsabiasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "abiasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsadamawasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "adamawasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsakwaibomsell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "akwaibomsell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsanambrasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "anambrasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbauchisell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "bauchisell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbayelsasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "bayelsasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbenuesell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "benuesell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsbornosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "bornosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordscrossriversell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "crossriversell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsdeltasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "deltasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsebonyisell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ebonyisell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsedosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "edosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsekitisell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ekitisell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsenugusell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "enugusell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsgombesell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "gombesell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsimosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "imosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsjigawasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "jigawasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordskadunasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kadunasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordskanosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kanosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordskatsinasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "katsinasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordskebbisell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kebbisell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordskogisell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kogisell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordskwarasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "kwarasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordslagossell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "lagossell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsnasarawasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "nasarawasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsnigersell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "nigersell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsogunsell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ogunsell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsondosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "ondosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsosunsell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "osunsell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsoyosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "oyosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})	
	$(document).ready(function(){$('#getrecordsplateausell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "plateausell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsriverssell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "riverssell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordssokotosell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "sokotosell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordstarabasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "tarabasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsyobesell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "yobesell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordszamfarasell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "zamfarasell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	$(document).ready(function(){$('#getrecordsfctsell').click(function(){var response = '';$("#loading").html('<img src="assets/vectors/loader.gif">');$.ajax({type: 'POST',url: "fctsell.php",async: false, success: function(text){$("#loading").ajaxComplete(function(){}).slideUp();$('.box_after_header_postsell').html(text);}});});})
	
	</script>
</body>
</html>
